/**
 * Generates an audit report in Markdown format from Scry JSON data
 */
export function generateMarkdownReport(data) {
  const p = data.project_overview || {};
  const v = p.vitality_score || {};
  const b = v.breakdown || {};
  const t = p.tech_stack || {};
  const a = data.architecture || {};
  const d = data.deep_dive_analysis || {};
  const u = data.ui_ux_audit || {};
  const r = data.risk_and_security_audit || {};
  const o = data.onboarding_and_usage || {};

  return `# 🚀 Scry Repository Intelligence Report: ${p.name || 'Repository Audit'}

> **Tagline:** ${p.tagline || 'N/A'}  
> **Elevator Pitch:** ${p.elevator_pitch || 'N/A'}  
> **Overall Vitality Score:** \`${v.overall_score || 0}/100\` — **${v.verdict || 'Reviewed'}**

---

## 📊 1. Vitality Score Breakdown
| Metric | Score | Status |
| :--- | :---: | :--- |
| 📖 **Documentation** | \`${b.documentation || 0}/100\` | ${b.documentation >= 80 ? '🟢 Strong' : '🟡 Needs Work'} |
| 🛠️ **Maintainability** | \`${b.maintainability || 0}/100\` | ${b.maintainability >= 80 ? '🟢 Strong' : '🟡 Needs Work'} |
| 🏛️ **Architecture Clarity** | \`${b.architecture_clarity || 0}/100\` | ${b.architecture_clarity >= 80 ? '🟢 Strong' : '🟡 Needs Work'} |
| 🛡️ **Security Posture** | \`${b.security_posture || 0}/100\` | ${b.security_posture >= 80 ? '🟢 Strong' : '🟡 Needs Work'} |

---

## 🛠️ 2. Tech Stack Matrix
- **Primary Language:** \`${t.primary_language || 'N/A'}\`
- **Languages:** ${(t.languages || []).map(l => `\`${l}\``).join(', ') || 'N/A'}
- **Frameworks & Libraries:** ${(t.frameworks || []).map(f => `\`${f}\``).join(', ') || 'None'}
- **Databases & ORM:** ${(t.databases || []).map(d => `\`${d}\``).join(', ') || 'None'}
- **Caching & Queues:** ${(t.caching_and_queues || []).map(c => `\`${c}\``).join(', ') || 'None'}
- **DevOps & Infrastructure:** ${(t.devops_and_cloud || []).map(dc => `\`${dc}\``).join(', ') || 'None'}

---

## 🏛️ 3. Architecture & Logic Flow
**Pattern:** ${a.pattern || 'Modular Architecture'}  
**Overview:** ${a.overview || 'N/A'}

### Architectural Diagram
\`\`\`mermaid
${a.logic_flow_mermaid || 'graph TD; A[Client] --> B[Server]'}
\`\`\`

### Key Entry Points
| File | Type | Purpose |
| :--- | :--- | :--- |
${(a.entry_points || []).map(e => `| \`${e.file}\` | \`${e.type}\` | ${e.purpose} |`).join('\n') || '| N/A | N/A | N/A |'}

---

## 🔬 4. Deep Dive Analysis
### Core Functions
${(d.core_functions || []).map(fn => `
#### \`${fn.symbol}\` (${fn.complexity ? fn.complexity.toUpperCase() : 'N/A'} Complexity)
- **File:** \`${fn.file}\`
- **Use Case:** ${fn.use_case || 'N/A'}
- **Logic:** ${fn.logic_summary || 'N/A'}
`).join('\n') || '_No critical functions extracted._'}

### API Surface
| Method | Endpoint | Auth Required | File | Description |
| :---: | :--- | :---: | :--- | :--- |
${(d.api_surface || []).map(api => `| **\`${api.method}\`** | \`${api.endpoint}\` | ${api.auth_required ? '🔒 Yes' : '🔓 No'} | \`${api.file}\` | ${api.description} |`).join('\n') || '| N/A | N/A | N/A | N/A | No public endpoints detected |'}

---

## 🛡️ 5. Risk & Security Audit
### Security Warnings
${(r.security_warnings || []).length > 0 ? (r.security_warnings || []).map(w => `
> ⚠️ **[${w.severity || 'WARNING'}] ${w.issue}**  
> **Location:** \`${w.location}\`  
> **Remediation:** ${w.remediation}
`).join('\n') : '✅ **No high-risk vulnerabilities detected.**'}

### Code Smells & Technical Debt
| Category | Description | Impact |
| :--- | :--- | :--- |
${(r.code_smells_and_technical_debt || []).map(s => `| **${s.category}** | ${s.description} | ${s.impact} |`).join('\n') || '| None | Clean code metrics | Minimal |'}

---

## 🚀 6. Onboarding & Quickstart
### Prerequisites
${(o.prerequisites || []).map(pr => `- ${pr}`).join('\n') || '- None listed'}

### Execution Steps
${(o.ai_quickstart_steps || []).map(st => `
**Step ${st.step}:** ${st.explanation}
\`\`\`bash
${st.command}
\`\`\`
`).join('\n') || '_No quickstart steps provided._'}

---
*Report automatically generated by [Scry](https://github.com).*
`;
}
